#!/bin/sh -ef

# ide.kaitai.io/devel needs to be rebuilt after we publish newest JS build of ksc to npm.

PROJECT='kaitai-io/kaitai_struct_webide'

echo "Triggering build for $PROJECT project..."
if [ -n "$KAITAI_STRUCT_WEBIDE_GITHUB_TOKEN" ]; then
	# Matches the type in kaitai_struct_webide's repository_dispatch trigger
	body='{"event_type":"rebuild"}'

	echo "$body"

	curl -v -fsSL \
		-X POST \
		-H "Accept: application/vnd.github+json" \
		-H "Authorization: Bearer $KAITAI_STRUCT_WEBIDE_GITHUB_TOKEN" \
		-H "X-GitHub-Api-Version: 2022-11-28" \
		-d "$body" \
		"https://api.github.com/repos/$PROJECT/dispatches"
else
	echo "No KAITAI_STRUCT_WEBIDE_GITHUB_TOKEN found!"
	exit 1
fi
