#!/bin/sh

# update-ci-status: updates CI status on protected site hosted at GitHub
# pages.
#
# Copyright (C) 2016 Kaitai Project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

echo -n 'Setting up bot key... '
echo "$BOT_SSH_KEY" | base64 -d >$HOME/bot_id
chmod 600 $HOME/bot_id
export GIT_SSH_COMMAND="ssh -i $HOME/bot_id"
echo OK

echo 'Cloning website repo...'
git clone git@github.com:kaitai-io/kaitai-io.github.io.git

echo 'Updating the report...'
cd kaitai-io.github.io
cp ../test_out/full.html ci/index.html

echo 'Committing...'
GIT_AUTHOR_NAME='Kaitai Bot' \
	GIT_AUTHOR_EMAIL='kaitai-bot@kaitai.io' \
	GIT_COMMITTER_NAME='Kaitai Bot' \
	GIT_COMMITTER_EMAIL='kaitai-bot@kaitai.io' \
		git ci -m "Updated with build results on $(date -Iseconds --utc)" \
			ci/index.html

echo 'Pushing...'
git push

echo -n 'Cleaning up the key... '
rm $HOME/bot_id
echo OK
